name: CI/CD - TaskMasterLite

on:
  push:
    branches: [ develop, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test Java + Maven
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: taskmaster-lite-jar
          path: target/*.jar

  dockerize-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    name: Dockerize and Publish to GHCR
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 for Maven rebuild
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Rebuild JAR
        run: mvn -B clean package

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=raw,value=latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  document-and-archive:
    needs: build-and-test
    runs-on: ubuntu-latest
    name: Generate and Archive Doxygen Documentation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v4
        with:
          name: taskmaster-lite-documentation
          path: docs/html/
